### ISSUE TITLE
Remove Fixed Function Pipeline

### ISSUE THREAD

**Issue by ptheywood** [Robadob/sdl_exp#28]
Remove the fixed function pipeline commands and do not using deprecated /  removed opengl commands , targetting a specific GL version (4.something)

**Comment by Robadob** [comment]
4.3 seems to be the best current option. It's the highest crap intel stuff like my laptop supports, and alot of new stuff was introduced at 4.3.

Only thing missing I'm aware of is named buffers which were introduced with 4.5. These *may* be more efficient that the older method of binding a buffer, then unbinding it around any methods that act on buffers, but replacing those at a later date should be rather painless.

**Comment by Robadob** [comment]
I've created a branch `4.3compat` for removing deprecated stuff: https://github.com/Robadob/sdl_exp/commit/ffce97e3017760800290055c6a27ebcd852ca2c6

So far I've enabled EXIT_ON_ERROR, enabled 4.3 forward compatibility (so we get deprecation errors on windows too), wrapped all gl calls with `GL_CALL()` (regex find-all did the trick, alot of stuff in comments or var names which also matched, so I may have missed 1 or two) and removed a handful of deprecated stuff (replaced some with printfs, to warn of their missing).

Current issues is `glVertexAttribPointer()` giving GL_INVALID_OPERATION, not obvious why, potentially need to fiddle with shaders to make use of VAOs.

Feel free to do work in this branch, I've got alot of other branches unfinished, so this isn't a high priority.

**Comment by Robadob** [comment]
I've managed to get the branch [4.3compat](https://github.com/Robadob/sdl_exp/tree/4.3compat) working, it's not the cleanest of code (a few basic features [axis] simply removed).

I'm working on gradually moving master over to proper 4.3 compatibility, remaining tasks:
*  VAO's
* Materials (Not really used/supported at current)
* Lighting (Not really used at current)
* ~~Axis~~

**Comment by Robadob** [comment]
Looking at a class like that below for creating raw models under VAOs, due to the complexity of construction.

Still stuck on the best way to handle generic attrib;
* We want shaders to be usable with multiple objects and vice versa
  * This is OK when only predictable attrib names are used (our reserved 4 vertex, normal, color, texCoord)
  * This is not OK when a generic attrib will have a different binding in multiple shaders as only one can be bound per VAO
    * The GL docs don't appear to state a max number of VAOs, so it may be feasible to create multiple VAOs within a model, adding one per shader when generic attribs are present (it's unlikely generic attribs will be widely used anyway)

```C++
/**
 * This class facilitates the construction of Model objects from raw vertex data
 * Call the relevant setTYPEAttribData() and addGenericAttribData() methods, providing all desired attributes
 * Once attributes have all been set call make_shared() or make_unique() to recieve a pointer to a RawModel
 * @note This class will store a copy of passed attrib arrays for it's duration
 * @note they will be deleted at destruction leaving only the copy in graphics memory
 */
class RawModelBuilder
{
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void setVertexAttribData(const glm::vec3 *vertices, unsigned int count, bool normalized=false);
    void setVertexAttribData(const glm::vec4 *vertices, unsigned int count, bool normalized=false);
    
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void setNormalAttribData(const glm::vec3 *normals, unsigned int count, bool normalized=false);
    void setNormalAttribData(const glm::vec4 *normals, unsigned int count, bool normalized=false);
    
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void setColorAttribData(const glm::vec3 *colors, unsigned int count, bool normalized=false);
    void setColorAttribData(const glm::vec4 *colors, unsigned int count, bool normalized=false);
    
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void setTexCoordAttribData(const glm::vec2 *texCoords, unsigned int count, bool normalized=false);
    void setTexCoordAttribData(const glm::vec3 *texCoords, unsigned int count, bool normalized=false);
    void setTexCoordAttribData(const glm::vec4 *texCoords, unsigned int count, bool normalized=false);
    
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void addGenericAttribData(const char* attribName, float *attribData, unsigned int count, bool normalized=false);
    void addGenericAttribData(const char* attribName, glm::vec2 *attribData, unsigned int count, bool normalized=false);
    void addGenericAttribData(const char* attribName, glm::vec3 *attribData, unsigned int count, bool normalized=false);
    void addGenericAttribData(const char* attribName, glm::vec4 *attribData, unsigned int count, bool normalized=false);
    
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void addGenericAttribData(const char* attribName, double *attribData, unsigned int count, bool normalized=false);
    void addGenericAttribData(const char* attribName, glm::dvec2 *attribData, unsigned int count, bool normalized=false);
    void addGenericAttribData(const char* attribName, glm::dvec3 *attribData, unsigned int count, bool normalized=false);
    void addGenericAttribData(const char* attribName, glm::dvec4 *attribData, unsigned int count, bool normalized=false);
    
    void addGenericAttribData(const char* attribName, int *attribData, unsigned int count);
    void addGenericAttribData(const char* attribName, glm::ivec2 *attribData, unsigned int count);
    void addGenericAttribData(const char* attribName, glm::ivec3 *attribData, unsigned int count);
    void addGenericAttribData(const char* attribName, glm::ivec4 *attribData, unsigned int count);
    
    void addGenericAttribData(const char* attribName, unsigned int *attribData, unsigned int count);
    void addGenericAttribData(const char* attribName, glm::uvec2 *attribData, unsigned int count);
    void addGenericAttribData(const char* attribName, glm::uvec3 *attribData, unsigned int count);
    void addGenericAttribData(const char* attribName, glm::uvec4 *attribData, unsigned int count);
    
    /**
     * @param @normalized Specifies whether the data should be normalised when accessed by the shader
     */
    void addGenericAttribData(const char* attribName, void *attribData, unsigned int count, GLint components, GLenum type, bool normalized=false);
};
```

**Comment by Robadob** [comment]
The version of `assimp_clean_merge` on my machine now execute under GL 4.3 forward compatibility without error. There are some messy changes in Entity holding me back from fully committing this right now, but it should be in soon.

**Comment by Robadob** [comment]
d3a31e3  
*If this isn't right the next large commit to the branch should solve it for the stock scenes. *
