### ISSUE TITLE
Viewport/FOV issues

### ISSUE THREAD

**Issue by Robadob** [Robadob/sdl_exp#31]
It's apparent that the viewport FOV is slightly screwy. Probably better to rewrite the frustum code to use a proportional FOV.

http://answers.unity3d.com/questions/888008/relationship-between-fov-and-aspect-ratio.html

**Comment by ptheywood** [comment]
https://glm.g-truc.net/0.9.4/api/a00151.html#gac2bbb4ae38c7cc549feefae5406517d7

Using `glm::perspective` or `glm::perpectiveFov` could be used in place of `glm::frustum` in `Visualisation::resizeWindow`

**Comment by Robadob** [comment]
Would have been useful to visually compare these, but I'll close it unless reported again.
